version: '2'

services:
  nginx-proxy:
    build: ./nginx-docker
    image: "nginx:1.19.4-alpine"
    network_mode: "host"
    container_name: nginx-proxy
    ports:
      - "8070:8070"
    volumes:
      - ".:/webroot"
